Add support for setExceptionMode
dart-lang/vm_service_client pull request #38
Opened 2018-07-17 14:52 UTC by DanTup

This adds a method to `Isolate` to set the exception mode and a test for each mode.

Fixes #37.

2018-07-17 15:54 UTC, DanTup commented
(I believe the Travis failure is because the tests are just broken in the latest SDKs. I ran against an older SDK and all is good. I think @kevmoo was setting this up recently and it's still WIP).

2018-07-17 18:07 UTC, jacob314 approved these changes
Please wait for @nex3 to approve as well.

2018-07-17 19:32 UTC, nex3 requested changes
Since you're providing the ability to set this, you should probably add a getter as well.

2018-07-17 19:32 UTC, nex3 commented on lib/src/isolate.dart
> +
Nit: extra newline

2018-07-17 19:32 UTC, nex3 commented on lib/src/isolate.dart
> +
Nit: extra newline

2018-07-17 19:32 UTC, nex3 commented on lib/src/isolate.dart
> +  /// The string name of the step type.
"step type" is wrong here

2018-07-17 19:40 UTC, nex3 commented
One other thing: please make sure all the APIs you add document the version of the protocol in which they first appear.

2018-07-18 07:55 UTC, DanTup commented
I've added the ability to get the pause mode and an additional test. Also added to changelog and updated version (I'll merge this with the other PR if they're landed around the same time).

@nex3 The test for the getter currently calls `toString()` since the `VMExceptionPauseMode` instances are different. Let me know if you'd prefer this was done another way (I was thinking a factory constructor could use the string to return the same instances, or we could override equality - not really sure what the usual done thing is in Dart).

> One other thing: please make sure all the APIs you add document the version of the protocol in which they first appear.

As far as I can tell from the docs, exceptionPauseMode has always been there (it's not in the changelog), though the stuff in the other PR is new, so I'll go back and update that one.

2018-07-18 08:03 UTC, DanTup commented
(btw, someone will need to merge this when happy with it as I don't have merge permissions here)

2018-07-23 07:41 UTC, DanTup commented
I've rebased on master since the version number I used has been used in `master` now. Lmk if you'd like any further changes.

2018-07-23 15:34 UTC, jacob314 approved these changes

2018-07-23 15:38 UTC, merged